// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvaYVKzWqeyPKhto54q1gUlOiM8Cgx4fE',
    appId: '1:474974800543:web:857521cd42e8bb3ff8f0aa',
    messagingSenderId: '474974800543',
    projectId: 'ecom-d4298',
    authDomain: 'ecom-d4298.firebaseapp.com',
    storageBucket: 'ecom-d4298.firebasestorage.app',
    measurementId: 'G-8EVRPKBYC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbwRFB_5TNyh13bY3H8x2rMRhLkf6zLnY',
    appId: '1:474974800543:android:6a2b08c7aae8e04bf8f0aa',
    messagingSenderId: '474974800543',
    projectId: 'ecom-d4298',
    storageBucket: 'ecom-d4298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKvauTNA9qjwCFYexwVecRBnJRwRtsmLM',
    appId: '1:474974800543:ios:528c136a8bf7e524f8f0aa',
    messagingSenderId: '474974800543',
    projectId: 'ecom-d4298',
    storageBucket: 'ecom-d4298.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );
}
